name: Test PDF rendering

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test PDF
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile PDF document from rmd
        uses: ./
        with:
          input_file: test/pdf.Rmd
          output_format: pdf_document

